### ISSUE TITLE
futu algo error occurred

### ISSUE THREAD

**Issue by a092cc** [billpwchan/futu_algo#41]
deployment futu_algo step by step , but when execute , exception occured.  how to fix? thanks 
(base) /home/xiaoming/anaconda3/bin/python3 main.py
Please rename stock_strategy_map_template.yml to stock_strategy_map.yml and update it.
Traceback (most recent call last):
  File "/home/xiaoming/develop/futu_algo/main.py", line 31, in <module>
    from engines import *
  File "/home/xiaoming/develop/futu_algo/engines/__init__.py", line 22, in <module>
    from .order_engine import *
  File "/home/xiaoming/develop/futu_algo/engines/order_engine.py", line 21, in <module>
    from futu import ModifyOrderOp, OpenHKTradeContext, OpenQuoteContext, OrderStatus, OrderType, RET_OK, \
ImportError: cannot import name 'ModifyOrderOp' from 'futu' (/home/xiaoming/anaconda3/lib/python3.9/site-packages/futu/__init__.py)

**Comment by billpwchan** [comment]
would you mind sharing your futu library version? I cannot reproduce this error from my end.
